version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_cinema
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_cinema
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinema.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - cinema_network

volumes:
  postgres_data:

networks:
  cinema_network:
